(function () {
  "use strict";

  /* V1 stays dependency-free and ES5-compatible for the VEWD/Opera browser. */
  var CONTENT = [
    { id: "tide", title: "Into the Blue", subtitle: "Documentary · 2024", description: "A quiet voyage through open water, where every horizon tells a different story.", art: "blue", video: "media/kerotv-test.mp4", duration: "12 min" },
    { id: "ember", title: "Ember City", subtitle: "Drama · 2023", description: "A city at dusk. Three lives, one last chance to change direction.", art: "orange", video: "media/kerotv-test.mp4", duration: "18 min" },
    { id: "orbit", title: "The Long Orbit", subtitle: "Series · S1 E1", description: "The crew of a small research ship finds a signal that should not be there.", art: "gold", video: "media/kerotv-test.mp4", duration: "24 min" },
    { id: "north", title: "Northbound", subtitle: "Adventure · 2022", description: "A road trip beyond the last familiar sign, made for the whole family.", art: "blue", video: "media/kerotv-test.mp4", duration: "21 min" },
    { id: "signal", title: "Signal Fires", subtitle: "Series · S1 E3", description: "Old friends reunite on a remote coast to finish an unfinished story.", art: "orange", video: "media/kerotv-test.mp4", duration: "26 min" },
    { id: "quiet", title: "Quiet Hours", subtitle: "Film · 2021", description: "Small moments become meaningful when the world finally slows down.", art: "gold", video: "media/kerotv-test.mp4", duration: "16 min" },
    { id: "garden", title: "Night Garden", subtitle: "Nature · 2024", description: "Step outside after sunset and discover a world that was always there.", art: "blue", video: "media/kerotv-test.mp4", duration: "14 min" },
    { id: "lastlight", title: "Last Light", subtitle: "Drama · 2020", description: "A warm, human story about leaving a light on for someone.", art: "orange", video: "media/kerotv-test.mp4", duration: "19 min" }
  ];
  var appState = { screen: "home", selected: CONTENT[0], homeFocus: 0, focus: 0, items: [], rowSize: 4, pointer: { x: null, y: null, moves: 0, enabled: false, lastAt: 0 }, guard: false, exitUntil: 0 };

  function on(el, name, fn) { if (!el) { return; } if (el.addEventListener) { el.addEventListener(name, fn, false); } else if (el.attachEvent) { el.attachEvent("on" + name, fn); } }
  function id(name) { return document.getElementById(name); }
  function text(el, value) { if (!el) { return; } if (typeof el.textContent !== "undefined") { el.textContent = value; } else { el.innerText = value; } }
  function add(el, name) { if (el && (" " + el.className + " ").indexOf(" " + name + " ") < 0) { el.className += " " + name; } }
  function remove(el, name) { if (el) { el.className = (" " + el.className + " ").replace(new RegExp(" " + name + " ", "g"), " ").replace(/^ | $/g, ""); } }
  function esc(value) { return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
  function byId(list, value) { var i; for (i = 0; i < list.length; i++) { if (list[i].id === value) { return list[i]; } } return null; }
  function card(item) { return '<button class="card" data-kind="content" data-id="' + item.id + '"><span class="card-art ' + item.art + '"></span><h3>' + esc(item.title) + '</h3><span class="card-meta">' + esc(item.subtitle) + '</span></button>'; }
  function homeHtml() { var html = '<section class="hero"><div class="hero-copy"><div class="eyebrow">FEATURED TONIGHT</div><h1>' + esc(CONTENT[0].title) + '</h1><p>' + esc(CONTENT[0].description) + '</p><div class="metadata">' + esc(CONTENT[0].subtitle) + ' &nbsp;·&nbsp; ' + CONTENT[0].duration + '</div><div class="detail-actions"><button class="action primary" data-kind="content" data-id="' + CONTENT[0].id + '">Open featured</button></div></div></section>'; html += '<section class="section"><div class="section-heading">Movies</div><div class="row">' + card(CONTENT[1]) + card(CONTENT[3]) + card(CONTENT[5]) + card(CONTENT[7]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Series</div><div class="row">' + card(CONTENT[2]) + card(CONTENT[4]) + card(CONTENT[6]) + card(CONTENT[0]) + '</div></section>'; return html; }
  function detailHtml(item) { return '<section class="detail"><div class="detail-content"><div class="eyebrow">DETAIL</div><h2>' + esc(item.title) + '</h2><div class="metadata">' + esc(item.subtitle) + ' &nbsp;·&nbsp; ' + item.duration + '</div><p>' + esc(item.description) + '</p><p class="muted">Ready to play over the verified KeroTV MP4 path.</p><div class="detail-actions"><button class="action primary" data-kind="play">Play now</button><button class="action secondary" data-kind="back">Back to Home</button></div></div><div class="detail-art ' + item.art + '"></div></section>'; }
  function playerHtml(item) { return '<section class="player"><video id="playerVideo" preload="auto" controls="controls"></video><div class="player-info"><h2>' + esc(item.title) + '</h2><span id="playerStatus" class="player-status">Loading MP4…</span><button class="action secondary player-back" data-kind="back">Back to detail</button></div></section>'; }
  function render() { var screen = id("screen"); text(id("screenLabel"), appState.screen === "home" ? "HOME" : appState.screen === "detail" ? "DETAIL" : "PLAYING"); if (appState.screen === "home") { screen.innerHTML = homeHtml(); } else if (appState.screen === "detail") { screen.innerHTML = detailHtml(appState.selected); } else { screen.innerHTML = playerHtml(appState.selected); } collectItems(); if (appState.screen === "player") { startPlayer(); } else { focus(appState.screen === "home" ? appState.homeFocus : 0); } }
  function collectItems() { var nodes = id("screen").getElementsByTagName("button"); var i; appState.items = []; for (i = 0; i < nodes.length; i++) { appState.items.push(nodes[i]); (function (button, index) { on(button, "click", function () { if (!appState.pointer.enabled) { if (appState.screen === "home") { appState.homeFocus = index; } activate(button); } }); }(nodes[i], i)); } }
  function focus(index) { var i; if (!appState.items.length) { return; } if (index < 0) { index = 0; } if (index >= appState.items.length) { index = appState.items.length - 1; } appState.focus = index; if (appState.screen === "home") { appState.homeFocus = index; } for (i = 0; i < appState.items.length; i++) { remove(appState.items[i], "is-focused"); appState.items[i].setAttribute("tabindex", i === index ? "0" : "-1"); } add(appState.items[index], "is-focused"); try { appState.items[index].focus(); } catch (ignore) {} }
  function move(direction) { var next = appState.focus; if (direction === "left") { next--; } else if (direction === "right") { next++; } else if (direction === "up") { next = appState.screen === "home" && next > 0 && next < 5 ? 0 : next - appState.rowSize; } else if (direction === "down") { next = appState.screen === "home" && next === 0 ? 1 : next + appState.rowSize; } focus(next); }
  function openDetail(item) { if (!item) { return; } appState.selected = item; appState.screen = "detail"; render(); }
  function startPlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } on(video, "loadstart", function () { text(status, "Loading MP4…"); }); on(video, "canplay", function () { text(status, "Ready · press Play if needed"); }); on(video, "playing", function () { text(status, "Playing"); }); on(video, "ended", function () { text(status, "Finished"); }); on(video, "error", function () { text(status, "Unable to play this MP4 on this browser"); add(status, "player-error"); }); video.src = appState.selected.video; try { video.load(); var result = video.play(); if (result && result.catch) { result.catch(function () { text(status, "Ready · press Play"); }); } } catch (error) { text(status, "Ready · press Play"); } }
  function activate(item) { if (!item) { return; } var kind = item.getAttribute("data-kind"); if (kind === "content") { openDetail(byId(CONTENT, item.getAttribute("data-id"))); } else if (kind === "play") { appState.screen = "player"; render(); } else if (kind === "back") { goBack(); } }
  function goBack() { if (appState.screen === "player") { var video = id("playerVideo"); if (video) { try { video.pause(); } catch (ignore) {} } appState.screen = "detail"; render(); } else if (appState.screen === "detail") { appState.screen = "home"; render(); } else { exitHint(); } }
  function keyCode(event) { return event.keyCode || event.which || 0; }
  function handleKey(event) { var code = keyCode(event); if (code === 37 || code === 38 || code === 39 || code === 40 || code === 13 || code === 8 || code === 27 || code === 461) { if (event.preventDefault) { event.preventDefault(); } } if (code === 37) { move("left"); } else if (code === 39) { move("right"); } else if (code === 38) { move("up"); } else if (code === 40) { move("down"); } else if (code === 13) { activate(appState.items[appState.focus]); } else if (code === 8 || code === 27 || code === 461) { goBack(); } return true; }
  function activatePointer() { if (!appState.pointer.enabled) { appState.pointer.enabled = true; add(document.body, "remote-pointer-mode"); text(id("inputMode"), "Sony pointer mode · focus controlled by KeroTV"); } }
  function pointerMove(event) { var x = typeof event.clientX === "number" ? event.clientX : event.screenX; var y = typeof event.clientY === "number" ? event.clientY : event.screenY; var dx, dy, now, direction; if (typeof x !== "number" || typeof y !== "number") { return; } if (appState.pointer.x === null) { appState.pointer.x = x; appState.pointer.y = y; return; } dx = x - appState.pointer.x; dy = y - appState.pointer.y; appState.pointer.x = x; appState.pointer.y = y; if (Math.abs(dx) < 3 && Math.abs(dy) < 3) { return; } now = new Date().getTime(); if (now - appState.pointer.lastAt < 140) { return; } appState.pointer.moves++; if (appState.pointer.moves >= 2) { activatePointer(); } if (!appState.pointer.enabled) { return; } appState.pointer.lastAt = now; direction = Math.abs(dx) >= Math.abs(dy) ? (dx < 0 ? "left" : "right") : (dy < 0 ? "up" : "down"); move(direction); }
  function pointerClick(event) { if (!appState.pointer.enabled) { return true; } if (event && event.preventDefault) { event.preventDefault(); } activate(appState.items[appState.focus]); return false; }
  function exitHint() { var now = new Date().getTime(); if (now < appState.exitUntil) { appState.guard = false; try { window.history.back(); } catch (ignore) {} return; } appState.exitUntil = now + 1600; text(id("inputMode"), "Press Back again quickly to leave KeroTV"); }
  function armGuard() { try { if (window.history && window.history.pushState) { window.history.replaceState({ kerotvBase: true }, document.title, window.location.href); window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); appState.guard = true; } } catch (ignore) {} }
  function clock() { var now = new Date(); text(id("clock"), (now.getHours() < 10 ? "0" : "") + now.getHours() + ":" + (now.getMinutes() < 10 ? "0" : "") + now.getMinutes()); }
  function init() { on(document, "keydown", handleKey); on(document, "mousemove", pointerMove); on(document, "click", pointerClick); on(window, "popstate", function () { if (appState.guard) { goBack(); try { window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); } catch (ignore) {} } }); clock(); window.setInterval(clock, 30000); render(); armGuard(); }
  if (document.readyState === "loading") { on(document, "DOMContentLoaded", init); } else { init(); }
}());
