(function () {
  "use strict";

  /* V1 stays dependency-free and ES5-compatible for the VEWD/Opera browser. */
  var CONTENT = [
    { id: "tide", title: "Into the Blue", subtitle: "Documentary · 2024", description: "A quiet voyage through open water, where every horizon tells a different story.", art: "blue", video: "media/kerotv-test.mp4", duration: "12 min" },
    { id: "ember", title: "Ember City", subtitle: "Drama · 2023", description: "A city at dusk. Three lives, one last chance to change direction.", art: "orange", video: "media/kerotv-test.mp4", duration: "18 min" },
    { id: "orbit", title: "The Long Orbit", subtitle: "Series · S1 E1", description: "The crew of a small research ship finds a signal that should not be there.", art: "gold", video: "media/kerotv-test.mp4", duration: "24 min" },
    { id: "north", title: "Northbound", subtitle: "Adventure · 2022", description: "A road trip beyond the last familiar sign, made for the whole family.", art: "blue", video: "media/kerotv-test.mp4", duration: "21 min" },
    { id: "signal", title: "Signal Fires", subtitle: "Series · S1 E3", description: "Old friends reunite on a remote coast to finish an unfinished story.", art: "orange", video: "media/kerotv-test.mp4", duration: "26 min" },
    { id: "quiet", title: "Quiet Hours", subtitle: "Film · 2021", description: "Small moments become meaningful when the world finally slows down.", art: "gold", video: "media/kerotv-test.mp4", duration: "16 min" },
    { id: "garden", title: "Night Garden", subtitle: "Nature · 2024", description: "Step outside after sunset and discover a world that was always there.", art: "blue", video: "media/kerotv-test.mp4", duration: "14 min" },
    { id: "lastlight", title: "Last Light", subtitle: "Drama · 2020", description: "A warm, human story about leaving a light on for someone.", art: "orange", video: "media/kerotv-test.mp4", duration: "19 min" },
    { id: "deadcells-av1", title: "Dead Cells · AV1 Test", subtitle: "AV1 · 720p120 · AAC", description: "Native KeroTV browser codec test using the original NVIDIA AV1 capture. Sony DLNA rejects this source; KeroTV will test the browser path directly.", art: "orange", video: "media/deadcells-av1.mp4", duration: "local test" },
    { id: "deadcells-h264", title: "Dead Cells · H.264 Control", subtitle: "H.264 · AAC", description: "Control version of the same clip. Add deadcells-h264.mp4 after conversion to compare AV1 and H.264 through exactly the same KeroTV path.", art: "blue", video: "media/deadcells-h264.mp4", duration: "local test" },
    { id: "subtitle-proof", title: "H.264 + SRT Proof", subtitle: "H.264 · AAC · KeroTV SRT overlay", description: "Known-good H.264 MP4 with subtitles rendered by KeroTV instead of the Sony DLNA player.", art: "gold", video: "media/kerotv-test.mp4", subtitleFile: "subtitles/kerotv-h264-proof.srt", duration: "proof test" },
    { id: "age-ultron-h264", title: "Age of Ultron · H.264 + SRT", subtitle: "Local H.264 · external SRT overlay", description: "Real-file subtitle test. Put the H.264 movie and Turkish SRT in the documented local paths; KeroTV keeps the video untouched and renders subtitles itself.", art: "orange", video: "media/age-of-ultron-h264.mp4", subtitleFile: "subtitles/age-of-ultron.srt", duration: "local movie" }
  ];
  var appState = { screen: "home", selected: CONTENT[0], homeFocus: 0, focus: 0, items: [], rowSize: 4, pointer: { x: null, y: null, moves: 0, enabled: false, lastAt: 0 }, guard: false, exitUntil: 0, subtitles: { cues: [], index: -1, source: null }, fullscreen: false, player: { controlsVisible: true, controlIndex: 0, hideTimer: null, seekSeconds: 10, subtitleSize: 50, pointerLocked: false, pictureMode: "fit", controlMode: false } };

  function on(el, name, fn) { if (!el) { return; } if (el.addEventListener) { el.addEventListener(name, fn, false); } else if (el.attachEvent) { el.attachEvent("on" + name, fn); } }
  function id(name) { return document.getElementById(name); }
  function text(el, value) { if (!el) { return; } if (typeof el.textContent !== "undefined") { el.textContent = value; } else { el.innerText = value; } }
  function add(el, name) { if (el && (" " + el.className + " ").indexOf(" " + name + " ") < 0) { el.className += " " + name; } }
  function remove(el, name) { if (el) { el.className = (" " + el.className + " ").replace(new RegExp(" " + name + " ", "g"), " ").replace(/^ | $/g, ""); } }
  function esc(value) { return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
  function byId(list, value) { var i; for (i = 0; i < list.length; i++) { if (list[i].id === value) { return list[i]; } } return null; }
  function card(item) { return '<button class="card" data-kind="content" data-id="' + item.id + '"><span class="card-art ' + item.art + '"></span><h3>' + esc(item.title) + '</h3><span class="card-meta">' + esc(item.subtitle) + '</span></button>'; }
  function homeHtml() { var html = '<section class="hero"><div class="hero-copy"><div class="eyebrow">FEATURED TONIGHT</div><h1>' + esc(CONTENT[0].title) + '</h1><p>' + esc(CONTENT[0].description) + '</p><div class="metadata">' + esc(CONTENT[0].subtitle) + ' &nbsp;·&nbsp; ' + CONTENT[0].duration + '</div><div class="detail-actions"><button class="action primary" data-kind="content" data-id="' + CONTENT[0].id + '">Open featured</button></div></div></section>'; html += '<section class="section"><div class="section-heading">Movies</div><div class="row">' + card(CONTENT[1]) + card(CONTENT[3]) + card(CONTENT[5]) + card(CONTENT[7]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Series</div><div class="row">' + card(CONTENT[2]) + card(CONTENT[4]) + card(CONTENT[6]) + card(CONTENT[0]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Codec Lab</div><div class="row">' + card(CONTENT[8]) + card(CONTENT[9]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Subtitle Lab</div><div class="row">' + card(CONTENT[10]) + card(CONTENT[11]) + '</div></section>'; return html; }
  function detailHtml(item) { var note = item.subtitleFile ? "KeroTV subtitle overlay enabled. Video remains untouched." : "Ready to play over the verified KeroTV MP4 path."; return '<section class="detail"><div class="detail-content"><div class="eyebrow">DETAIL</div><h2>' + esc(item.title) + '</h2><div class="metadata">' + esc(item.subtitle) + ' &nbsp;·&nbsp; ' + item.duration + '</div><p>' + esc(item.description) + '</p><p class="muted">' + esc(note) + '</p><div class="detail-actions"><button class="action primary" data-kind="play">Play now</button><button class="action secondary" data-kind="back">Back to Home</button></div></div><div class="detail-art ' + item.art + '"></div></section>'; }
  function playerHtml(item) { return '<section class="player"><div id="videoStage" class="video-stage"><video id="playerVideo" preload="auto"></video><div id="subtitleOverlay" class="subtitle-overlay"></div><div id="seekOsd" class="seek-osd"></div><div id="playerChrome" class="player-chrome"><div class="player-title">' + esc(item.title) + '</div><div class="player-progress"><div id="playerProgressFill" class="player-progress-fill"></div></div><div class="player-time"><span id="playerCurrent">0:00</span><span id="playerDuration">0:00</span></div><div class="player-controls"><button class="player-control" data-kind="subtitle-smaller">Sub −</button><span id="subtitleSizeLabel" class="subtitle-size-label">50px</span><button class="player-control" data-kind="subtitle-larger">Sub +</button><button class="player-control" data-kind="picture-mode" id="pictureModeButton">Fit</button><button class="player-control" data-kind="fullscreen">Fullscreen</button><button class="player-control" data-kind="back">Back</button></div><div class="player-meta"><span id="playerStatus">Loading MP4…</span><span id="subtitleStatus"></span><span id="resolutionInfo" class="resolution-info"></span><span class="player-help">4/6 seek · 2/8 seçenek · OK seç · Play/Pause kumanda tuşları</span></div></div></div></section>'; }
  function render() { var screen = id("screen"); text(id("screenLabel"), appState.screen === "home" ? "HOME" : appState.screen === "detail" ? "DETAIL" : "PLAYING"); if (appState.screen === "home") { screen.innerHTML = homeHtml(); } else if (appState.screen === "detail") { screen.innerHTML = detailHtml(appState.selected); } else { screen.innerHTML = playerHtml(appState.selected); } collectItems(); if (appState.screen === "player") { startPlayer(); } else { focus(appState.screen === "home" ? appState.homeFocus : 0); } }
  function collectItems() { var nodes = id("screen").getElementsByTagName("button"); var i; appState.items = []; for (i = 0; i < nodes.length; i++) { appState.items.push(nodes[i]); (function (button, index) { on(button, "click", function () { if (!appState.pointer.enabled) { if (appState.screen === "home") { appState.homeFocus = index; } activate(button); } }); }(nodes[i], i)); } }
  function focus(index) { var i; if (!appState.items.length) { return; } if (index < 0) { index = 0; } if (index >= appState.items.length) { index = appState.items.length - 1; } appState.focus = index; if (appState.screen === "home") { appState.homeFocus = index; } for (i = 0; i < appState.items.length; i++) { remove(appState.items[i], "is-focused"); appState.items[i].setAttribute("tabindex", i === index ? "0" : "-1"); } add(appState.items[index], "is-focused"); try { appState.items[index].focus(); } catch (ignore) {} }
  function move(direction) { var next = appState.focus; if (direction === "left") { next--; } else if (direction === "right") { next++; } else if (direction === "up") { next = appState.screen === "home" && next > 0 && next < 5 ? 0 : next - appState.rowSize; } else if (direction === "down") { next = appState.screen === "home" && next === 0 ? 1 : next + appState.rowSize; } focus(next); }
  function openDetail(item) { if (!item) { return; } appState.selected = item; setFullscreenClass(false); appState.screen = "detail"; render(); }
  function loadPlayerPreferences() { var value, picture; try { value = parseInt(window.localStorage.getItem("kerotv.subtitleSize"), 10); picture = window.localStorage.getItem("kerotv.pictureMode"); } catch (ignore) { value = 0; picture = null; } if (value >= 30 && value <= 80) { appState.player.subtitleSize = value; } if (picture === "fit" || picture === "zoom") { appState.player.pictureMode = picture; } }
  function saveSubtitleSize() { try { window.localStorage.setItem("kerotv.subtitleSize", String(appState.player.subtitleSize)); } catch (ignore) {} }
  function applySubtitleSize() { var overlay = id("subtitleOverlay"); var label = id("subtitleSizeLabel"); if (overlay) { overlay.style.fontSize = appState.player.subtitleSize + "px"; } if (label) { text(label, appState.player.subtitleSize + "px"); } }
  function changeSubtitleSize(delta) { var next = appState.player.subtitleSize + delta; if (next < 30) { next = 30; } if (next > 80) { next = 80; } appState.player.subtitleSize = next; applySubtitleSize(); saveSubtitleSize(); showPlayerControls(); }
  function savePictureMode() { try { window.localStorage.setItem("kerotv.pictureMode", appState.player.pictureMode); } catch (ignore) {} }
  function applyPictureMode() { var video = id("playerVideo"); var button = id("pictureModeButton"); if (video) { remove(video, "picture-fit"); remove(video, "picture-zoom"); add(video, appState.player.pictureMode === "zoom" ? "picture-zoom" : "picture-fit"); } if (button) { text(button, appState.player.pictureMode === "zoom" ? "Zoom" : "Fit"); } }
  function togglePictureMode() { appState.player.pictureMode = appState.player.pictureMode === "fit" ? "zoom" : "fit"; applyPictureMode(); savePictureMode(); showPlayerControls(); }
  function updateResolutionInfo(video) { var uiW = window.innerWidth || document.documentElement.clientWidth || 0; var uiH = window.innerHeight || document.documentElement.clientHeight || 0; var screenW = window.screen ? window.screen.width : 0; var screenH = window.screen ? window.screen.height : 0; var dpr = window.devicePixelRatio || 1; var media = video && video.videoWidth ? video.videoWidth + "×" + video.videoHeight : "—"; text(id("resolutionInfo"), "Video " + media + " · UI " + uiW + "×" + uiH + " · Screen " + screenW + "×" + screenH + " · DPR " + dpr); }
  function formatTime(seconds) { var value = isFinite(seconds) && seconds > 0 ? Math.floor(seconds) : 0; var hours = Math.floor(value / 3600); var minutes = Math.floor((value % 3600) / 60); var secs = value % 60; if (hours > 0) { return hours + ":" + (minutes < 10 ? "0" : "") + minutes + ":" + (secs < 10 ? "0" : "") + secs; } return minutes + ":" + (secs < 10 ? "0" : "") + secs; }
  function updatePlayerProgress(video) { var fill = id("playerProgressFill"); var duration = video && isFinite(video.duration) ? video.duration : 0; var current = video && isFinite(video.currentTime) ? video.currentTime : 0; var percent = duration > 0 ? Math.max(0, Math.min(100, (current / duration) * 100)) : 0; if (fill) { fill.style.width = percent + "%"; } text(id("playerCurrent"), formatTime(current)); text(id("playerDuration"), formatTime(duration)); }
  function updatePlayPauseLabel(video) { return video; }
  function clearPlayerHideTimer() { if (appState.player.hideTimer) { window.clearTimeout(appState.player.hideTimer); appState.player.hideTimer = null; } }
  function hidePlayerControls() { var chrome = id("playerChrome"); var video = id("playerVideo"); if (!chrome || !video || video.paused || appState.player.controlMode) { return; } remove(chrome, "is-visible"); appState.player.controlsVisible = false; }
  function schedulePlayerHide() { clearPlayerHideTimer(); if (appState.player.controlMode) { return; } if (id("playerVideo") && !id("playerVideo").paused) { appState.player.hideTimer = window.setTimeout(hidePlayerControls, 2800); } }
  function showPlayerControls() { var chrome = id("playerChrome"); if (chrome) { add(chrome, "is-visible"); appState.player.controlsVisible = true; } schedulePlayerHide(); }
  function showSeekOsd(label) { var osd = id("seekOsd"); if (!osd) { return; } text(osd, label); add(osd, "is-visible"); window.setTimeout(function () { remove(osd, "is-visible"); }, 650); }
  function seekPlayer(delta) { var video = id("playerVideo"); var target; if (!video || !isFinite(video.duration)) { return; } target = (video.currentTime || 0) + delta; if (target < 0) { target = 0; } if (target > video.duration) { target = video.duration; } try { video.currentTime = target; } catch (ignore) {} appState.subtitles.index = -1; updateSubtitle(video); updatePlayerProgress(video); showSeekOsd((delta > 0 ? "+" : "") + delta + "s"); showPlayerControls(); }
  function playerControls() { var root = id("playerChrome"); var nodes, result = [], i; if (!root) { return result; } nodes = root.getElementsByTagName("button"); for (i = 0; i < nodes.length; i++) { result.push(nodes[i]); } return result; }
  function focusPlayerControl(index) { var controls = playerControls(); var i; if (!controls.length) { return; } if (index < 0) { index = controls.length - 1; } if (index >= controls.length) { index = 0; } appState.player.controlIndex = index; for (i = 0; i < controls.length; i++) { remove(controls[i], "is-focused"); } add(controls[index], "is-focused"); try { controls[index].focus(); } catch (ignore) {} showPlayerControls(); }
  function enterPlayerControlMode() { appState.player.controlMode = true; add(id("playerChrome"), "control-mode"); focusPlayerControl(appState.player.controlIndex); clearPlayerHideTimer(); }
  function exitPlayerControlMode() { var controls = playerControls(); var i; appState.player.controlMode = false; remove(id("playerChrome"), "control-mode"); for (i = 0; i < controls.length; i++) { remove(controls[i], "is-focused"); try { controls[i].blur(); } catch (ignore) {} } schedulePlayerHide(); }
  function movePlayerControl(delta) { if (!appState.player.controlMode) { appState.player.controlMode = true; add(id("playerChrome"), "control-mode"); focusPlayerControl(appState.player.controlIndex); clearPlayerHideTimer(); return; } focusPlayerControl(appState.player.controlIndex + delta); }
  function activatePlayerControl() { var controls = playerControls(); if (controls.length && controls[appState.player.controlIndex]) { activate(controls[appState.player.controlIndex]); } else { togglePlayer(); } }
  function requestPlayerPointerLock() { var stage = id("videoStage"); var request; if (!stage) { return; } request = stage.requestPointerLock || stage.webkitRequestPointerLock || stage.mozRequestPointerLock; if (request) { try { request.call(stage); } catch (ignore) {} } }
  function releasePlayerPointerLock() { var exit = document.exitPointerLock || document.webkitExitPointerLock || document.mozExitPointerLock; if (exit) { try { exit.call(document); } catch (ignore) {} } appState.player.pointerLocked = false; }
  function syncPointerLockState() { var locked = document.pointerLockElement || document.webkitPointerLockElement || document.mozPointerLockElement; appState.player.pointerLocked = !!locked; }
  function playerRemoteDirection(direction) { if (direction === "left") { seekPlayer(-appState.player.seekSeconds); } else if (direction === "right") { seekPlayer(appState.player.seekSeconds); } else if (direction === "up") { movePlayerControl(-1); } else if (direction === "down") { movePlayerControl(1); } }
  function parseSubtitleTime(value) { var match = String(value).replace(/^\s+|\s+$/g, "").match(/^(\d+):(\d+):(\d+)[,.](\d+)$/); var ms; if (!match) { return null; } ms = parseInt(match[4], 10); if (match[4].length === 1) { ms *= 100; } else if (match[4].length === 2) { ms *= 10; } else if (match[4].length > 3) { ms = parseInt(match[4].substr(0, 3), 10); } return parseInt(match[1], 10) * 3600 + parseInt(match[2], 10) * 60 + parseInt(match[3], 10) + (ms / 1000); }
  function parseSrt(raw) { var normalized = String(raw || "").replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").replace(/\r/g, "\n"); var blocks = normalized.split(/\n\s*\n/); var cues = []; var i, lines, timeLine, arrow, start, end, bodyStart, body; for (i = 0; i < blocks.length; i++) { lines = blocks[i].split("\n"); if (!lines.length) { continue; } timeLine = lines[0]; bodyStart = 1; if (timeLine.indexOf("-->") < 0 && lines.length > 1) { timeLine = lines[1]; bodyStart = 2; } arrow = timeLine.indexOf("-->"); if (arrow < 0) { continue; } start = parseSubtitleTime(timeLine.substring(0, arrow)); end = parseSubtitleTime(timeLine.substring(arrow + 3)); if (start === null || end === null || end <= start) { continue; } body = lines.slice(bodyStart).join("\n").replace(/^\s+|\s+$/g, ""); if (body) { cues.push({ start: start, end: end, text: body }); } } return cues; }
  function subtitleHtml(value) { var source = String(value || ""); var safe; source = source.replace(/<br\s*\/?\s*>/gi, "\n"); safe = esc(source); safe = safe.replace(/&lt;i&gt;/gi, "<i>").replace(/&lt;\/i&gt;/gi, "</i>"); safe = safe.replace(/&lt;b&gt;/gi, "<b>").replace(/&lt;\/b&gt;/gi, "</b>"); safe = safe.replace(/&lt;u&gt;/gi, "<u>").replace(/&lt;\/u&gt;/gi, "</u>"); safe = safe.replace(/&lt;[^&]*?&gt;/g, ""); safe = safe.replace(/\n/g, "<br>"); return safe; }
  function renderSubtitleOverlay(value) { var overlay = id("subtitleOverlay"); if (!overlay) { return; } overlay.innerHTML = subtitleHtml(value); }
  function clearSubtitleOverlay() { var overlay = id("subtitleOverlay"); if (overlay) { overlay.innerHTML = ""; } }
  function findSubtitleCue(cues, current) { var low = 0; var high = cues.length - 1; var mid; while (low <= high) { mid = Math.floor((low + high) / 2); if (current < cues[mid].start) { high = mid - 1; } else if (current >= cues[mid].end) { low = mid + 1; } else { return mid; } } return -1; }
  function updateSubtitle(video) { var cues = appState.subtitles.cues; var overlay = id("subtitleOverlay"); var current, index; if (!video || !overlay || !cues.length) { clearSubtitleOverlay(); return; } current = video.currentTime || 0; index = appState.subtitles.index; if (index < 0 || index >= cues.length || current < cues[index].start || current >= cues[index].end) { index = findSubtitleCue(cues, current); appState.subtitles.index = index; } if (index >= 0) { renderSubtitleOverlay(cues[index].text); } else { clearSubtitleOverlay(); } }
  function decodeSubtitlePayload(payload) { if (window.JSON && JSON.parse) { return JSON.parse(payload); } return eval("(" + payload + ")"); }
  function loadSubtitles(path, video) { var status = id("subtitleStatus"); var xhr, requestPath; appState.subtitles.cues = []; appState.subtitles.index = -1; appState.subtitles.source = path || null; clearSubtitleOverlay(); if (!path) { text(status, ""); return; } text(status, " · Subtitles loading…"); requestPath = path + (path.indexOf("?") >= 0 ? "&" : "?") + "format=json"; try { xhr = new XMLHttpRequest(); xhr.open("GET", requestPath, true); xhr.onreadystatechange = function () { var raw; if (xhr.readyState !== 4) { return; } if ((xhr.status >= 200 && xhr.status < 300) || xhr.status === 0) { try { raw = decodeSubtitlePayload(xhr.responseText); } catch (decodeError) { text(status, " · Subtitle Unicode decode failed"); return; } appState.subtitles.cues = parseSrt(raw); appState.subtitles.index = -1; if (appState.subtitles.cues.length) { text(status, " · Subtitles ON · " + appState.subtitles.cues.length + " cues"); updateSubtitle(video); } else { text(status, " · Subtitle file loaded but no valid cues"); } } else { text(status, " · Subtitle file unavailable"); } }; xhr.send(null); } catch (error) { text(status, " · Subtitle load failed"); } }
  function startPlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } loadPlayerPreferences(); applySubtitleSize(); applyPictureMode(); updateResolutionInfo(video); on(video, "loadstart", function () { text(status, "Loading MP4…"); }); on(video, "loadedmetadata", function () { updatePlayerProgress(video); updateResolutionInfo(video); applyPictureMode(); }); on(video, "durationchange", function () { updatePlayerProgress(video); }); on(video, "canplay", function () { text(status, "Ready"); updatePlayerProgress(video); updatePlayPauseLabel(video); }); on(video, "playing", function () { text(status, "Playing"); updatePlayPauseLabel(video); schedulePlayerHide(); }); on(video, "pause", function () { text(status, "Paused"); updatePlayPauseLabel(video); showPlayerControls(); }); on(video, "timeupdate", function () { updateSubtitle(video); updatePlayerProgress(video); }); on(video, "seeked", function () { appState.subtitles.index = -1; updateSubtitle(video); updatePlayerProgress(video); }); on(video, "ended", function () { text(status, "Finished"); updatePlayPauseLabel(video); clearSubtitleOverlay(); showPlayerControls(); }); on(video, "error", function () { text(status, "Unable to play this MP4 on this browser"); }); loadSubtitles(appState.selected.subtitleFile, video); video.src = appState.selected.video; add(document.body, "player-active"); appState.player.controlMode = false; showPlayerControls(); try { video.load(); var result = video.play(); if (result && result.catch) { result.catch(function () { text(status, "Ready"); updatePlayPauseLabel(video); showPlayerControls(); }); } } catch (error) { text(status, "Ready"); } }
  function fullscreenElement() { return document.fullscreenElement || document.webkitFullscreenElement || document.mozFullScreenElement || document.msFullscreenElement || null; }
  function setFullscreenClass(enabled) { var player = id("screen"); appState.fullscreen = enabled; if (enabled) { add(document.body, "kerotv-fullscreen"); if (player) { add(player, "kerotv-fullscreen-screen"); } } else { remove(document.body, "kerotv-fullscreen"); if (player) { remove(player, "kerotv-fullscreen-screen"); } } }
  function enterKeroFullscreen() { var stage = id("videoStage"); var request; if (!stage) { return; } setFullscreenClass(true); request = stage.requestFullscreen || stage.webkitRequestFullscreen || stage.mozRequestFullScreen || stage.msRequestFullscreen; if (request) { try { request.call(stage); } catch (ignore) {} } requestPlayerPointerLock(); showPlayerControls(); }
  function exitKeroFullscreen() { var exit = document.exitFullscreen || document.webkitExitFullscreen || document.mozCancelFullScreen || document.msExitFullscreen; releasePlayerPointerLock(); if (exit && fullscreenElement()) { try { exit.call(document); } catch (ignore) {} } setFullscreenClass(false); }
  function toggleKeroFullscreen() { if (appState.fullscreen || fullscreenElement()) { exitKeroFullscreen(); } else { enterKeroFullscreen(); } }
  function syncFullscreenState() { var active = !!fullscreenElement(); if (!active && appState.fullscreen) { setFullscreenClass(false); } else if (active && !appState.fullscreen) { setFullscreenClass(true); } }
  function activate(item) { var kind; if (!item) { return; } kind = item.getAttribute("data-kind"); if (kind === "content") { openDetail(byId(CONTENT, item.getAttribute("data-id"))); } else if (kind === "play") { appState.screen = "player"; render(); enterKeroFullscreen(); } else if (kind === "subtitle-smaller") { changeSubtitleSize(-4); enterPlayerControlMode(); } else if (kind === "subtitle-larger") { changeSubtitleSize(4); enterPlayerControlMode(); } else if (kind === "picture-mode") { togglePictureMode(); enterPlayerControlMode(); } else if (kind === "fullscreen") { toggleKeroFullscreen(); } else if (kind === "back") { goBack(); } }
  function goBack() { if (appState.screen === "player") { var video = id("playerVideo"); clearPlayerHideTimer(); appState.player.controlMode = false; releasePlayerPointerLock(); if (appState.fullscreen || fullscreenElement()) { exitKeroFullscreen(); } if (video) { try { video.pause(); } catch (ignore) {} } remove(document.body, "player-active"); setFullscreenClass(false); appState.screen = "detail"; render(); } else if (appState.screen === "detail") { appState.screen = "home"; render(); } else { exitHint(); } }
  function keyCode(event) { return event.keyCode || event.which || 0; }
  function directionFromKeyCode(code) {
    if (code === 50 || code === 98) { return "up"; }     /* 2 / numpad 2 */
    if (code === 56 || code === 104) { return "down"; }   /* 8 / numpad 8 */
    if (code === 52 || code === 100) { return "left"; }  /* 4 / numpad 4 */
    if (code === 54 || code === 102) { return "right"; } /* 6 / numpad 6 */
    if (code === 38) { return "up"; }
    if (code === 40) { return "down"; }
    if (code === 37) { return "left"; }
    if (code === 39) { return "right"; }
    return null;
  }
  function isDirectionalCode(code) { return directionFromKeyCode(code) !== null; }
  function handleKey(event) {
    var code = keyCode(event);
    var direction = directionFromKeyCode(code);
    var handled = false;

    if (appState.screen === "player") {
      if (direction) {
        playerRemoteDirection(direction);
        handled = true;
      } else if (code === 13) {
        if (!appState.player.controlsVisible) {
          showPlayerControls();
          enterPlayerControlMode();
        } else {
          if (!appState.player.controlMode) { enterPlayerControlMode(); }
          else { activatePlayerControl(); }
        }
        handled = true;
      } else if (code === 415) {
        playPlayer();
        handled = true;
      } else if (code === 19) {
        pausePlayer();
        handled = true;
      } else if (code === 179) {
        togglePlayer();
        handled = true;
      } else if (code === 413 || code === 178) {
        stopPlayer();
        handled = true;
      } else if (code === 412) {
        seekPlayer(-appState.player.seekSeconds);
        handled = true;
      } else if (code === 417) {
        seekPlayer(appState.player.seekSeconds);
        handled = true;
      } else if (code === 8 || code === 27 || code === 461) {
        goBack();
        handled = true;
      }
    } else {
      if (direction) {
        move(direction);
        handled = true;
      } else if (code === 13) {
        activate(appState.items[appState.focus]);
        handled = true;
      } else if (code === 8 || code === 27 || code === 461) {
        goBack();
        handled = true;
      }
    }

    if (handled && event.preventDefault) { event.preventDefault(); }
    return true;
  }
  function activatePointer() { if (!appState.pointer.enabled) { appState.pointer.enabled = true; add(document.body, "remote-pointer-mode"); text(id("inputMode"), "2/4/6/8 primary · Sony pointer D-pad fallback"); } }
  function pointerMove(event) { var x = typeof event.clientX === "number" ? event.clientX : event.screenX; var y = typeof event.clientY === "number" ? event.clientY : event.screenY; var dx, dy, now, direction; if (appState.player.pointerLocked) { dx = event.movementX || event.webkitMovementX || event.mozMovementX || 0; dy = event.movementY || event.webkitMovementY || event.mozMovementY || 0; } else { if (typeof x !== "number" || typeof y !== "number") { return; } if (appState.pointer.x === null) { appState.pointer.x = x; appState.pointer.y = y; return; } dx = x - appState.pointer.x; dy = y - appState.pointer.y; appState.pointer.x = x; appState.pointer.y = y; } if (Math.abs(dx) < 3 && Math.abs(dy) < 3) { return; } now = new Date().getTime(); if (now - appState.pointer.lastAt < 135) { return; } appState.pointer.moves++; if (appState.pointer.moves >= 1) { activatePointer(); } if (!appState.pointer.enabled) { return; } appState.pointer.lastAt = now; direction = Math.abs(dx) >= Math.abs(dy) ? (dx < 0 ? "left" : "right") : (dy < 0 ? "up" : "down"); if (appState.screen === "player") { showPlayerControls(); playerRemoteDirection(direction); } else { move(direction); } }
  function playPlayer() { var video = id("playerVideo"); var status = id("playerStatus"); var result; if (!video) { return; } try { result = video.play(); if (result && result.catch) { result.catch(function () { text(status, "Ready"); }); } text(status, "Playing"); showPlayerControls(); } catch (ignore) {} }
  function pausePlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } try { video.pause(); text(status, "Paused"); showPlayerControls(); } catch (ignore) {} }
  function stopPlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } try { video.pause(); video.currentTime = 0; appState.subtitles.index = -1; updateSubtitle(video); updatePlayerProgress(video); text(status, "Stopped"); showPlayerControls(); } catch (ignore) {} }
  function togglePlayer() { var video = id("playerVideo"); if (!video) { return; } if (video.paused || video.ended) { playPlayer(); } else { pausePlayer(); } }
  function pointerClick(event) { var focused, target; if (!appState.pointer.enabled) { return true; } if (event && event.preventDefault) { event.preventDefault(); } if (event && event.stopPropagation) { event.stopPropagation(); } target = event ? (event.target || event.srcElement) : null; if (appState.screen === "player") { showPlayerControls(); if (target && target.getAttribute && target.getAttribute("data-kind")) { activate(target); } return false; } focused = appState.items[appState.focus]; activate(focused); return false; }
  function exitHint() { var now = new Date().getTime(); if (now < appState.exitUntil) { appState.guard = false; try { window.history.back(); } catch (ignore) {} return; } appState.exitUntil = now + 1600; text(id("inputMode"), "Press Back again quickly to leave KeroTV"); }
  function armGuard() { try { if (window.history && window.history.pushState) { window.history.replaceState({ kerotvBase: true }, document.title, window.location.href); window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); appState.guard = true; } } catch (ignore) {} }
  function clock() { var now = new Date(); text(id("clock"), (now.getHours() < 10 ? "0" : "") + now.getHours() + ":" + (now.getMinutes() < 10 ? "0" : "") + now.getMinutes()); }
  function init() { on(document, "keydown", handleKey); on(window, "resize", function () { if (appState.screen === "player") { updateResolutionInfo(id("playerVideo")); } }); on(document, "mousemove", pointerMove); on(document, "click", pointerClick); on(document, "fullscreenchange", syncFullscreenState); on(document, "webkitfullscreenchange", syncFullscreenState); on(document, "mozfullscreenchange", syncFullscreenState); on(document, "MSFullscreenChange", syncFullscreenState); on(document, "pointerlockchange", syncPointerLockState); on(document, "webkitpointerlockchange", syncPointerLockState); on(document, "mozpointerlockchange", syncPointerLockState); on(window, "popstate", function () { if (appState.guard) { goBack(); if (appState.guard) { try { window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); } catch (ignore) {} } } }); clock(); window.setInterval(clock, 30000); render(); armGuard(); }
  if (document.readyState === "loading") { on(document, "DOMContentLoaded", init); } else { init(); }
}());
