(function () {
  "use strict";

  /* V1 stays dependency-free and ES5-compatible for the VEWD/Opera browser. */
  var CONTENT = [
    { id: "tide", title: "Into the Blue", subtitle: "Documentary · 2024", description: "A quiet voyage through open water, where every horizon tells a different story.", art: "blue", video: "media/kerotv-test.mp4", duration: "12 min" },
    { id: "ember", title: "Ember City", subtitle: "Drama · 2023", description: "A city at dusk. Three lives, one last chance to change direction.", art: "orange", video: "media/kerotv-test.mp4", duration: "18 min" },
    { id: "orbit", title: "The Long Orbit", subtitle: "Series · S1 E1", description: "The crew of a small research ship finds a signal that should not be there.", art: "gold", video: "media/kerotv-test.mp4", duration: "24 min" },
    { id: "north", title: "Northbound", subtitle: "Adventure · 2022", description: "A road trip beyond the last familiar sign, made for the whole family.", art: "blue", video: "media/kerotv-test.mp4", duration: "21 min" },
    { id: "signal", title: "Signal Fires", subtitle: "Series · S1 E3", description: "Old friends reunite on a remote coast to finish an unfinished story.", art: "orange", video: "media/kerotv-test.mp4", duration: "26 min" },
    { id: "quiet", title: "Quiet Hours", subtitle: "Film · 2021", description: "Small moments become meaningful when the world finally slows down.", art: "gold", video: "media/kerotv-test.mp4", duration: "16 min" },
    { id: "garden", title: "Night Garden", subtitle: "Nature · 2024", description: "Step outside after sunset and discover a world that was always there.", art: "blue", video: "media/kerotv-test.mp4", duration: "14 min" },
    { id: "lastlight", title: "Last Light", subtitle: "Drama · 2020", description: "A warm, human story about leaving a light on for someone.", art: "orange", video: "media/kerotv-test.mp4", duration: "19 min" },
    { id: "deadcells-av1", title: "Dead Cells · AV1 Test", subtitle: "AV1 · 720p120 · AAC", description: "Native KeroTV browser codec test using the original NVIDIA AV1 capture. Sony DLNA rejects this source; KeroTV will test the browser path directly.", art: "orange", video: "media/deadcells-av1.mp4", duration: "local test" },
    { id: "deadcells-h264", title: "Dead Cells · H.264 Control", subtitle: "H.264 · AAC", description: "Control version of the same clip. Add deadcells-h264.mp4 after conversion to compare AV1 and H.264 through exactly the same KeroTV path.", art: "blue", video: "media/deadcells-h264.mp4", duration: "local test" },
    { id: "subtitle-proof", title: "H.264 + SRT Proof", subtitle: "H.264 · AAC · KeroTV SRT overlay", description: "Known-good H.264 MP4 with subtitles rendered by KeroTV instead of the Sony DLNA player.", art: "gold", video: "media/kerotv-test.mp4", subtitleFile: "subtitles/kerotv-h264-proof.srt", duration: "proof test" },
    { id: "age-ultron-h264", title: "Age of Ultron · H.264 + SRT", subtitle: "Local H.264 · external SRT overlay", description: "Real-file subtitle test. Put the H.264 movie and Turkish SRT in the documented local paths; KeroTV keeps the video untouched and renders subtitles itself.", art: "orange", video: "media/age-of-ultron-h264.mp4", subtitleFile: "subtitles/age-of-ultron.srt", duration: "local movie" }
  ];
  var appState = { screen: "home", selected: CONTENT[0], homeFocus: 0, focus: 0, items: [], rowSize: 4, pointer: { x: null, y: null, moves: 0, enabled: false, lastAt: 0 }, guard: false, exitUntil: 0, subtitles: { cues: [], index: -1, source: null }, fullscreen: false };

  function on(el, name, fn) { if (!el) { return; } if (el.addEventListener) { el.addEventListener(name, fn, false); } else if (el.attachEvent) { el.attachEvent("on" + name, fn); } }
  function id(name) { return document.getElementById(name); }
  function text(el, value) { if (!el) { return; } if (typeof el.textContent !== "undefined") { el.textContent = value; } else { el.innerText = value; } }
  function add(el, name) { if (el && (" " + el.className + " ").indexOf(" " + name + " ") < 0) { el.className += " " + name; } }
  function remove(el, name) { if (el) { el.className = (" " + el.className + " ").replace(new RegExp(" " + name + " ", "g"), " ").replace(/^ | $/g, ""); } }
  function esc(value) { return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
  function byId(list, value) { var i; for (i = 0; i < list.length; i++) { if (list[i].id === value) { return list[i]; } } return null; }
  function card(item) { return '<button class="card" data-kind="content" data-id="' + item.id + '"><span class="card-art ' + item.art + '"></span><h3>' + esc(item.title) + '</h3><span class="card-meta">' + esc(item.subtitle) + '</span></button>'; }
  function homeHtml() { var html = '<section class="hero"><div class="hero-copy"><div class="eyebrow">FEATURED TONIGHT</div><h1>' + esc(CONTENT[0].title) + '</h1><p>' + esc(CONTENT[0].description) + '</p><div class="metadata">' + esc(CONTENT[0].subtitle) + ' &nbsp;·&nbsp; ' + CONTENT[0].duration + '</div><div class="detail-actions"><button class="action primary" data-kind="content" data-id="' + CONTENT[0].id + '">Open featured</button></div></div></section>'; html += '<section class="section"><div class="section-heading">Movies</div><div class="row">' + card(CONTENT[1]) + card(CONTENT[3]) + card(CONTENT[5]) + card(CONTENT[7]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Series</div><div class="row">' + card(CONTENT[2]) + card(CONTENT[4]) + card(CONTENT[6]) + card(CONTENT[0]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Codec Lab</div><div class="row">' + card(CONTENT[8]) + card(CONTENT[9]) + '</div></section>'; html += '<section class="section"><div class="section-heading">Subtitle Lab</div><div class="row">' + card(CONTENT[10]) + card(CONTENT[11]) + '</div></section>'; return html; }
  function detailHtml(item) { var note = item.subtitleFile ? "KeroTV subtitle overlay enabled. Video remains untouched." : "Ready to play over the verified KeroTV MP4 path."; return '<section class="detail"><div class="detail-content"><div class="eyebrow">DETAIL</div><h2>' + esc(item.title) + '</h2><div class="metadata">' + esc(item.subtitle) + ' &nbsp;·&nbsp; ' + item.duration + '</div><p>' + esc(item.description) + '</p><p class="muted">' + esc(note) + '</p><div class="detail-actions"><button class="action primary" data-kind="play">Play now</button><button class="action secondary" data-kind="back">Back to Home</button></div></div><div class="detail-art ' + item.art + '"></div></section>'; }
  function playerHtml(item) { return '<section class="player"><div class="video-stage"><video id="playerVideo" preload="auto" controls="controls"></video><div id="subtitleOverlay" class="subtitle-overlay"></div></div><div class="player-info"><h2>' + esc(item.title) + '</h2><span id="playerStatus" class="player-status">Loading MP4…</span><span id="subtitleStatus" class="subtitle-status"></span><button class="action secondary player-fullscreen" data-kind="fullscreen">Fullscreen</button><button class="action secondary player-back" data-kind="back">Back to detail</button></div></section>'; }
  function render() { var screen = id("screen"); text(id("screenLabel"), appState.screen === "home" ? "HOME" : appState.screen === "detail" ? "DETAIL" : "PLAYING"); if (appState.screen === "home") { screen.innerHTML = homeHtml(); } else if (appState.screen === "detail") { screen.innerHTML = detailHtml(appState.selected); } else { screen.innerHTML = playerHtml(appState.selected); } collectItems(); if (appState.screen === "player") { startPlayer(); } else { focus(appState.screen === "home" ? appState.homeFocus : 0); } }
  function collectItems() { var nodes = id("screen").getElementsByTagName("button"); var i; appState.items = []; for (i = 0; i < nodes.length; i++) { appState.items.push(nodes[i]); (function (button, index) { on(button, "click", function () { if (!appState.pointer.enabled) { if (appState.screen === "home") { appState.homeFocus = index; } activate(button); } }); }(nodes[i], i)); } }
  function focus(index) { var i; if (!appState.items.length) { return; } if (index < 0) { index = 0; } if (index >= appState.items.length) { index = appState.items.length - 1; } appState.focus = index; if (appState.screen === "home") { appState.homeFocus = index; } for (i = 0; i < appState.items.length; i++) { remove(appState.items[i], "is-focused"); appState.items[i].setAttribute("tabindex", i === index ? "0" : "-1"); } add(appState.items[index], "is-focused"); try { appState.items[index].focus(); } catch (ignore) {} }
  function move(direction) { var next = appState.focus; if (direction === "left") { next--; } else if (direction === "right") { next++; } else if (direction === "up") { next = appState.screen === "home" && next > 0 && next < 5 ? 0 : next - appState.rowSize; } else if (direction === "down") { next = appState.screen === "home" && next === 0 ? 1 : next + appState.rowSize; } focus(next); }
  function openDetail(item) { if (!item) { return; } appState.selected = item; setFullscreenClass(false); appState.screen = "detail"; render(); }
  function parseSubtitleTime(value) { var match = String(value).replace(/^\s+|\s+$/g, "").match(/^(\d+):(\d+):(\d+)[,.](\d+)$/); var ms; if (!match) { return null; } ms = parseInt(match[4], 10); if (match[4].length === 1) { ms *= 100; } else if (match[4].length === 2) { ms *= 10; } else if (match[4].length > 3) { ms = parseInt(match[4].substr(0, 3), 10); } return parseInt(match[1], 10) * 3600 + parseInt(match[2], 10) * 60 + parseInt(match[3], 10) + (ms / 1000); }
  function parseSrt(raw) { var normalized = String(raw || "").replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").replace(/\r/g, "\n"); var blocks = normalized.split(/\n\s*\n/); var cues = []; var i, lines, timeLine, arrow, start, end, bodyStart, body; for (i = 0; i < blocks.length; i++) { lines = blocks[i].split("\n"); if (!lines.length) { continue; } timeLine = lines[0]; bodyStart = 1; if (timeLine.indexOf("-->") < 0 && lines.length > 1) { timeLine = lines[1]; bodyStart = 2; } arrow = timeLine.indexOf("-->"); if (arrow < 0) { continue; } start = parseSubtitleTime(timeLine.substring(0, arrow)); end = parseSubtitleTime(timeLine.substring(arrow + 3)); if (start === null || end === null || end <= start) { continue; } body = lines.slice(bodyStart).join("\n").replace(/^\s+|\s+$/g, ""); if (body) { cues.push({ start: start, end: end, text: body }); } } return cues; }
  function clearSubtitleOverlay() { text(id("subtitleOverlay"), ""); }
  function findSubtitleCue(cues, current) { var low = 0; var high = cues.length - 1; var mid; while (low <= high) { mid = Math.floor((low + high) / 2); if (current < cues[mid].start) { high = mid - 1; } else if (current >= cues[mid].end) { low = mid + 1; } else { return mid; } } return -1; }
  function updateSubtitle(video) { var cues = appState.subtitles.cues; var overlay = id("subtitleOverlay"); var current, index; if (!video || !overlay || !cues.length) { clearSubtitleOverlay(); return; } current = video.currentTime || 0; index = appState.subtitles.index; if (index < 0 || index >= cues.length || current < cues[index].start || current >= cues[index].end) { index = findSubtitleCue(cues, current); appState.subtitles.index = index; } if (index >= 0) { text(overlay, cues[index].text); } else { text(overlay, ""); } }
  function decodeSubtitlePayload(payload) { if (window.JSON && JSON.parse) { return JSON.parse(payload); } return eval("(" + payload + ")"); }
  function loadSubtitles(path, video) { var status = id("subtitleStatus"); var xhr, requestPath; appState.subtitles.cues = []; appState.subtitles.index = -1; appState.subtitles.source = path || null; clearSubtitleOverlay(); if (!path) { text(status, ""); return; } text(status, " · Subtitles loading…"); requestPath = path + (path.indexOf("?") >= 0 ? "&" : "?") + "format=json"; try { xhr = new XMLHttpRequest(); xhr.open("GET", requestPath, true); xhr.onreadystatechange = function () { var raw; if (xhr.readyState !== 4) { return; } if ((xhr.status >= 200 && xhr.status < 300) || xhr.status === 0) { try { raw = decodeSubtitlePayload(xhr.responseText); } catch (decodeError) { text(status, " · Subtitle Unicode decode failed"); return; } appState.subtitles.cues = parseSrt(raw); appState.subtitles.index = -1; if (appState.subtitles.cues.length) { text(status, " · Subtitles ON · " + appState.subtitles.cues.length + " cues"); updateSubtitle(video); } else { text(status, " · Subtitle file loaded but no valid cues"); } } else { text(status, " · Subtitle file unavailable"); } }; xhr.send(null); } catch (error) { text(status, " · Subtitle load failed"); } }
  function startPlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } on(video, "loadstart", function () { text(status, "Loading MP4…"); }); on(video, "canplay", function () { text(status, "Ready · press Play if needed"); }); on(video, "playing", function () { text(status, "Playing"); }); on(video, "timeupdate", function () { updateSubtitle(video); }); on(video, "seeked", function () { appState.subtitles.index = -1; updateSubtitle(video); }); on(video, "ended", function () { text(status, "Finished"); clearSubtitleOverlay(); }); on(video, "error", function () { text(status, "Unable to play this MP4 on this browser"); add(status, "player-error"); }); loadSubtitles(appState.selected.subtitleFile, video); video.src = appState.selected.video; try { video.load(); var result = video.play(); if (result && result.catch) { result.catch(function () { text(status, "Ready · press Play"); }); } } catch (error) { text(status, "Ready · press Play"); } }
  function fullscreenElement() { return document.fullscreenElement || document.webkitFullscreenElement || document.mozFullScreenElement || document.msFullscreenElement || null; }
  function setFullscreenClass(enabled) { var player = id("screen"); appState.fullscreen = enabled; if (enabled) { add(document.body, "kerotv-fullscreen"); if (player) { add(player, "kerotv-fullscreen-screen"); } } else { remove(document.body, "kerotv-fullscreen"); if (player) { remove(player, "kerotv-fullscreen-screen"); } } }
  function enterKeroFullscreen() { var stage = id("playerVideo") ? id("playerVideo").parentNode : null; var request; if (!stage) { return; } setFullscreenClass(true); request = stage.requestFullscreen || stage.webkitRequestFullscreen || stage.mozRequestFullScreen || stage.msRequestFullscreen; if (request) { try { request.call(stage); } catch (ignore) {} } }
  function exitKeroFullscreen() { var exit = document.exitFullscreen || document.webkitExitFullscreen || document.mozCancelFullScreen || document.msExitFullscreen; if (exit && fullscreenElement()) { try { exit.call(document); } catch (ignore) {} } setFullscreenClass(false); }
  function toggleKeroFullscreen() { if (appState.fullscreen || fullscreenElement()) { exitKeroFullscreen(); } else { enterKeroFullscreen(); } }
  function syncFullscreenState() { var active = !!fullscreenElement(); if (!active && appState.fullscreen) { setFullscreenClass(false); } else if (active && !appState.fullscreen) { setFullscreenClass(true); } }
  function activate(item) { if (!item) { return; } var kind = item.getAttribute("data-kind"); if (kind === "content") { openDetail(byId(CONTENT, item.getAttribute("data-id"))); } else if (kind === "play") { appState.screen = "player"; render(); } else if (kind === "fullscreen") { toggleKeroFullscreen(); } else if (kind === "back") { goBack(); } }
  function goBack() { if (appState.screen === "player" && (appState.fullscreen || fullscreenElement())) { exitKeroFullscreen(); return; } if (appState.screen === "player") { var video = id("playerVideo"); if (video) { try { video.pause(); } catch (ignore) {} } appState.screen = "detail"; render(); } else if (appState.screen === "detail") { appState.screen = "home"; render(); } else { exitHint(); } }
  function keyCode(event) { return event.keyCode || event.which || 0; }
  function handleKey(event) { var code = keyCode(event); if (code === 37 || code === 38 || code === 39 || code === 40 || code === 13 || code === 8 || code === 27 || code === 461) { if (event.preventDefault) { event.preventDefault(); } } if (code === 37) { move("left"); } else if (code === 39) { move("right"); } else if (code === 38) { move("up"); } else if (code === 40) { move("down"); } else if (code === 13) { activate(appState.items[appState.focus]); } else if (code === 8 || code === 27 || code === 461) { goBack(); } return true; }
  function activatePointer() { if (!appState.pointer.enabled) { appState.pointer.enabled = true; add(document.body, "remote-pointer-mode"); text(id("inputMode"), "Sony pointer mode · focus controlled by KeroTV"); } }
  function pointerMove(event) { var x = typeof event.clientX === "number" ? event.clientX : event.screenX; var y = typeof event.clientY === "number" ? event.clientY : event.screenY; var dx, dy, now, direction; if (typeof x !== "number" || typeof y !== "number") { return; } if (appState.pointer.x === null) { appState.pointer.x = x; appState.pointer.y = y; return; } dx = x - appState.pointer.x; dy = y - appState.pointer.y; appState.pointer.x = x; appState.pointer.y = y; if (Math.abs(dx) < 3 && Math.abs(dy) < 3) { return; } now = new Date().getTime(); if (now - appState.pointer.lastAt < 140) { return; } appState.pointer.moves++; if (appState.pointer.moves >= 2) { activatePointer(); } if (!appState.pointer.enabled) { return; } appState.pointer.lastAt = now; direction = Math.abs(dx) >= Math.abs(dy) ? (dx < 0 ? "left" : "right") : (dy < 0 ? "up" : "down"); move(direction); }
  function togglePlayer() { var video = id("playerVideo"); var status = id("playerStatus"); if (!video) { return; } try { if (video.paused || video.ended) { var result = video.play(); if (result && result.catch) { result.catch(function () { text(status, "Ready · press Play"); }); } } else { video.pause(); text(status, "Paused"); } } catch (ignore) {} }
  function pointerClick(event) { var focused; if (!appState.pointer.enabled) { return true; } if (event && event.preventDefault) { event.preventDefault(); } if (event && event.stopPropagation) { event.stopPropagation(); } focused = appState.items[appState.focus]; if (appState.screen === "player") { if (focused && focused.getAttribute("data-kind")) { activate(focused); } else { togglePlayer(); } return false; } activate(focused); return false; }
  function exitHint() { var now = new Date().getTime(); if (now < appState.exitUntil) { appState.guard = false; try { window.history.back(); } catch (ignore) {} return; } appState.exitUntil = now + 1600; text(id("inputMode"), "Press Back again quickly to leave KeroTV"); }
  function armGuard() { try { if (window.history && window.history.pushState) { window.history.replaceState({ kerotvBase: true }, document.title, window.location.href); window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); appState.guard = true; } } catch (ignore) {} }
  function clock() { var now = new Date(); text(id("clock"), (now.getHours() < 10 ? "0" : "") + now.getHours() + ":" + (now.getMinutes() < 10 ? "0" : "") + now.getMinutes()); }
  function init() { on(document, "keydown", handleKey); on(document, "mousemove", pointerMove); on(document, "click", pointerClick); on(document, "fullscreenchange", syncFullscreenState); on(document, "webkitfullscreenchange", syncFullscreenState); on(document, "mozfullscreenchange", syncFullscreenState); on(document, "MSFullscreenChange", syncFullscreenState); on(window, "popstate", function () { if (appState.guard) { goBack(); if (appState.guard) { try { window.history.pushState({ kerotvGuard: true }, document.title, window.location.href); } catch (ignore) {} } } }); clock(); window.setInterval(clock, 30000); render(); armGuard(); }
  if (document.readyState === "loading") { on(document, "DOMContentLoaded", init); } else { init(); }
}());
